# Generated by Django 2.2.7 on 2019-12-16 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='pet',
            managers=[
            ],
        ),
    ]
