# Generated by Django 2.2.7 on 2019-12-17 02:49

from django.db import migrations, models
import django.db.models.deletion
import pets.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_auto_20191216_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('photo', models.ImageField(null=True, upload_to=pets.models.pets_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(db_column='pet_id', on_delete=django.db.models.deletion.CASCADE, to='pets.Pet')),
            ],
        ),
    ]
