# Generated by Django 2.2.8 on 2019-12-17 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import donations.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=128)),
                ('long_description', models.TextField()),
                ('status', models.CharField(choices=[('started', 'started'), ('finalized', 'finalized'), ('stopped', 'stopped'), ('canceled', 'canceled')], default='started', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(null=True)),
                ('canceled_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.Category')),
                ('donor', models.ForeignKey(db_column='user_id_donor', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonationImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to=donations.models.donations_images_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.ForeignKey(db_column='donation_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='donations.Donation')),
            ],
        ),
    ]
